### ISSUE TITLE
Add comment when closing issue automatically

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-ml#6]
When we close an invalid issue we should leave the following comment:

> We have closed this issue automatically as we suspect it is invalid. If we made a mistake, please file a new issue and try to provide more context.

**Comment by miketaylr** [comment]
Here's what SV uses in their template, maybe we can incorporate. 

> Due to the lack of additional info, I'll close this issue as Incomplete.
Reporter, unfortunately having so little details about the issue you are experiencing, we cannot help you with it. Please leave a comment with more details, or file a new report and we will gladly investigate this further.

**Comment by johngian** [comment]
Fixed after: https://github.com/mozilla/webcompat-ml-deploy/commit/b783f79202198422a1a8ef3230980e01378cf763
