### ISSUE TITLE
Change the milestone when closing issue automatically

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [mozilla/webcompat-ml#8]
While we're automatically closing issues, we should also change the milestone for them, into Invalid or Incomplete.

Since the message is
`We have closed this issue automatically as we suspect it is invalid. If we made a mistake, please file a new issue and try to provide more context.`
maybe Invalid is the better option.

**Comment by miketaylr** [comment]
cc @johngian

**Comment by johngian** [comment]
I updated the automation. Let's wait for the changes to kick in to production and I will close this issue.

**Comment by johngian** [comment]
I verified that this worked as expected here: https://github.com/webcompat/web-bugs/issues/46673
